name: Fetch upstream
on: 
    schedule:
        - cron: '0 0 * * 1,4'
    push:
      branches: AUTHORSHIP
jobs:
    fetch:
        name: Fetch upstream
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: AUTHORSHIP
            - name: Run updater
              run: |
                ./update.sh